repos:
  - repo: local
    hooks:
      # - id: black
      #   name: black
      #   entry: black
      #   language: system
      #   types: [python]

      # - id: isort
      #   name: isort
      #   entry: isort
      #   language: system
      #   types: [python]
      #   args: ["--profile", "black"]

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        exclude: ^backend/migrations/
        args: ["--max-line-length=100", "--extend-ignore=E203,W503, E501"]

      - id: pytest
        name: pytest
        entry: bash -c 'cd backend && pytest'
        language: system
        files: \.py$
        pass_filenames: false
        stages: [pre-commit]
