"""add supabase_uid to user

Revision ID: 03260d9e792a
Revises: 13234618113c
Create Date: 2026-04-11 15:37:42.712995

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '03260d9e792a'
down_revision = '13234618113c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supabase_uid', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_supabase_uid'), ['supabase_uid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_supabase_uid'))
        batch_op.drop_column('supabase_uid')

    # ### end Alembic commands ###
