"""add exercise categories

Revision ID: 0abbbedde9e2
Revises: 2ea8b3484e8a
Create Date: 2026-02-25 08:51:27.356993

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0abbbedde9e2'
down_revision = '2ea8b3484e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_category_name'), ['name'], unique=True)

    op.create_table('exercise_categories',
    sa.Column('exercise_definition_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['exercise_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_definition_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exercise_definition_id', 'category_id')
    )

    # Seed standard categories
    seed_names = [
        "Cardio",
        "Core",
        "Flexibility",
        "Legs",
        "Lower Body",
        "Pull",
        "Push",
        "Upper Body",
    ]
    op.bulk_insert(
        sa.table("exercise_category", sa.column("name", sa.String)),
        [{"name": n} for n in seed_names],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_categories')
    with op.batch_alter_table('exercise_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_category_name'))

    op.drop_table('exercise_category')
    # ### end Alembic commands ###
