"""workout-status is_done

Revision ID: 13234618113c
Revises: 65eeeaaf3dea
Create Date: 2026-03-02 20:24:08.062419

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '13234618113c'
down_revision = '65eeeaaf3dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_done', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_column('is_done')

    # ### end Alembic commands ###
