"""add duration field

Revision ID: 29de48c9eeca
Revises: 
Create Date: 2026-02-16 23:46:12.864714

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '29de48c9eeca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('counting_type', sa.String(length=10), server_default='reps', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_column('counting_type')

    # ### end Alembic commands ###
