"""add is_template to workout

Revision ID: 2ea8b3484e8a
Revises: 57f4ec4775b1
Create Date: 2026-02-24 20:34:45.379316

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2ea8b3484e8a'
down_revision = '57f4ec4775b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_template', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_column('is_template')

    # ### end Alembic commands ###
