"""drop password_hash column from user (legacy Flask-Login auth retired)

Revision ID: 4d407a87e6c1
Revises: 175157103655
Create Date: 2026-09-15 00:00:00.000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4d407a87e6c1'
down_revision = '175157103655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###
