"""add progression-levels

Revision ID: 57f4ec4775b1
Revises: aba545880542
Create Date: 2026-02-22 14:16:47.637746

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '57f4ec4775b1'
down_revision = 'aba545880542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progression_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_definition_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('level_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_definition_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    op.drop_table('progression_levels')
    # ### end Alembic commands ###
