"""add notes to workout and exercise

Revision ID: 7c1e9a2b4f30
Revises: 4d407a87e6c1
Create Date: 2026-09-29 00:00:00.000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7c1e9a2b4f30'
down_revision = '4d407a87e6c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_column('notes')

    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
