"""add uploaded_image table

Revision ID: c1c659752107
Revises: 7c1e9a2b4f30
Create Date: 2026-09-30 18:58:41.273101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c659752107'
down_revision = '7c1e9a2b4f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    with op.batch_alter_table('uploaded_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploaded_image_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploaded_image_user_id'))

    op.drop_table('uploaded_image')
    # ### end Alembic commands ###
