"""add planned_date to workout

Revision ID: f23d9ab2f9ed
Revises: 36005226877b
Create Date: 2026-09-12 21:00:00.000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f23d9ab2f9ed'
down_revision = '36005226877b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planned_date', sa.Date(), nullable=True))
        batch_op.create_index(
            batch_op.f('ix_workout_planned_date'), ['planned_date'], unique=False
        )

    # ### end Alembic commands ###

    # Backfill existing rows from their own timestamp's date, not a single
    # fixed "today" -- historical workouts should keep their real calendar day.
    op.execute(
        "UPDATE workout SET planned_date = DATE(timestamp) WHERE planned_date IS NULL"
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_planned_date'))
        batch_op.drop_column('planned_date')

    # ### end Alembic commands ###
